export default [
  {
    id: 1,
    bgColor: '#b8d6e5',
    image: '/img/monuments.png',
    title: 'Les monuments',
    desc: 'Site interactif présentant des monuments français sur une carte avec leur description.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/Julie-Charles16/monuments-france.git',
    demo: 'https://Julie-Charles16.github.io/monuments-france/',
  },
  {
    id: 2,
    bgColor: '#e5b88a',
    image: '/img/cv.png',
    title: 'CV numérique',
    desc: 'CV numérique retraçant mon parcours professionnel.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/Julie-Charles16/cv-numerique.git',
    demo: 'https://Julie-Charles16.github.io/cv-numerique/',
  },
  {
    id: 3,
    bgColor: '#8fccaf',
    image: '/img/pidu.png',
    title: 'Pidu',
    desc: "Application éducative pour apprendre l'anglais.",
    tech: ['React', 'NodeJs', 'Neon'],
    github: 'https://github.com/Julie-Charles16/pidu-jch.git',
    demo: 'https://pidu-jch.vercel.app/',
  },
  {
    id: 4,
    bgColor: '#8ab5e5',
    image: '/img/Tangram.png',
    title: 'Tangram',
    desc: 'Jeu interactif permettant de reconstituer des formes à partir de pièces géométriques.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/Julie-Charles16/tangram.git',
    demo: 'https://Julie-Charles16.github.io/tangram',
  },
  {
    id: 5,
    bgColor: '#e5db8a',
    image: '/img/syntax.png',
    title: 'Syntax Showdown',
    desc: 'Jeu où les langages de programmation s’affrontent en avatars dans une arène digitale.',
    tech: ['PHP', 'MySQL', 'Docker'],
    github: 'https://github.com/Julie-Charles16/Syntax-Showdown.git',
  },
]
