export default [
  {
    id: 1,
    bgColor: '#b8d6e5',
    image: '/img/monuments.png',
    title: 'Les monuments',
    desc: 'Site interactif affichant des monuments français avec leur description et localisation sur une carte.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/2024-dwwm-bsm-p4/monuments.git',
    demo: 'https://2024-dwwm-bsm-p4.github.io/monuments-jch/',
  },
  {
    id: 2,
    bgColor: '#e5b88a',
    image: '/img/cv.png',
    title: 'CV numérique',
    desc: 'CV numérique retraçant mon parcours professionnel.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/2024-dwwm-bsm-p4/cv.git',
    demo: 'https://2024-dwwm-bsm-p4.github.io/cv-jch/',
  },
  {
    id: 3,
    bgColor: '#8fccaf',
    image: '/img/pidu.png',
    title: 'Pidu',
    desc: "Application éducative pour apprendre l'anglais.",
    tech: ['React', 'NodeJs', 'Neon'],
    github: 'https://github.com/code-dev-pro/-Pidu-JCH-MLE.git',
    demo: 'https://pidu-jch-3uah5jh3v-laurenthenemanedukeasycoms-projects.vercel.app',
  },
  {
    id: 4,
    bgColor: '#8ab5e5',
    image: '/img/Tangram.png',
    title: 'Tangram',
    desc: 'Jeu interactif permettant de reconstituer des formes à partir de pièces géométriques.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/2024-dwwm-bsm-p4/tangram-mle.git',
  },
  {
    id: 5,
    bgColor: '#e5db8a',
    image: '/img/syntax.png',
    title: 'Syntax Showdown',
    desc: 'Jeu où les langages de programmation s’affrontent en avatars dans une arène digitale.',
    tech: ['PHP', 'MySQL', 'Docker'],
    github: 'https://github.com/2024-dwwm-bsm-p4/random-fight-mla.git',
  },
]
